<?php
/**
 * Class to manage Spectra Extensions.
 *
 * @package Spectra
 */

namespace Spectra;

use Spectra\Extensions\ResponsiveControls;
use Spectra\Traits\Singleton;

defined( 'ABSPATH' ) || exit;

/**
 * Class to manage Spectra Extensions.
 *
 * @since 1.0.0
 */
class ExtensionManager {

	use Singleton;

	/**
	 * Initializes the extension manager by registering all extensions.
	 *
	 * @since 1.0.0
	 * @return void
	 */
	public function init() {
		$this->init_extensions();

		add_action( 'enqueue_block_editor_assets', array( $this, 'register_extensions' ) );
	}

	/**
	 * Initializes all extensions by calling their init() method.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function init_extensions() {
		( ResponsiveControls::instance() )->init();
	}

	/**
	 * Enqueues all extensions editor assets.
	 *
	 * This method scans the 'build/extensions/' directory for subdirectories containing
	 * an 'index.asset.php' file, and calls the enqueue_editor_extension_assets() method
	 * for each of them.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function register_extensions() {
		$extensions_dir = SPECTRA_DIR . 'build/extensions/';

		if ( ! is_dir( $extensions_dir ) || ! is_readable( $extensions_dir ) ) {
			return;
		}

		$extension_files = glob( $extensions_dir . '*/index.asset.php' );

		if ( empty( $extension_files ) ) {
			return;
		}

		// Process all extensions.
		foreach ( $extension_files as $extension_file ) {
			$this->enqueue_editor_extension_assets( $extension_file );
		}
	}

	/**
	 * Enqueues editor assets for a given extension.
	 *
	 * @since 1.0.0
	 *
	 * @param string $extension_file Path to the extension's asset file.
	 * @return void
	 */
	private function enqueue_editor_extension_assets( $extension_file ) {
		if ( ! file_exists( $extension_file ) ) {
			return;
		}

		$extension_dir = dirname( $extension_file );
		$folder_name   = basename( $extension_dir ); // Get extension folder name.
		$handle        = "spectra-extension-{$folder_name}-editor";
		$script_url    = SPECTRA_URL . "build/extensions/{$folder_name}/index.js";
		$script_path   = SPECTRA_DIR . "build/extensions/{$folder_name}/index.js";

		if ( ! file_exists( $script_path ) ) {
			return;
		}

		// Load the asset file generated by Webpack.
		$asset_file = include_once $extension_file;

		// Handle case where include_once returns true (already included).
		if ( true === $asset_file ) {
			$asset_file = array(
				'dependencies' => array(),
				'version'      => '1.0.0',
			);
		}

		// Ensure we have a valid asset file array.
		if ( ! is_array( $asset_file ) ) {
			return;
		}

		wp_enqueue_script(
			$handle,
			$script_url,
			isset( $asset_file['dependencies'] ) ? $asset_file['dependencies'] : array(),
			isset( $asset_file['version'] ) ? $asset_file['version'] : '1.0.0',
			true
		);
		wp_set_script_translations( $handle, 'spectra', SPECTRA_DIR . 'languages' );

		// Enqueue extension styles if they exist.
		$this->enqueue_extension_styles( $folder_name );

		/**
		 * Fires after enqueuing the editor assets for the given extension.
		 *
		 * @since 1.0.0
		 */
		do_action( 'spectra_extensions_editor_assets', $folder_name, $asset_file );
	}

	/**
	 * Enqueues styles for a given extension from the build/styles/extensions directory.
	 *
	 * @since 1.0.0
	 *
	 * @param string $folder_name The extension folder name.
	 * @return void
	 */
	private function enqueue_extension_styles( $folder_name ) {
		$style_path = SPECTRA_DIR . "build/styles/extensions/{$folder_name}.css";

		if ( ! file_exists( $style_path ) ) {
			return;
		}

		$handle = "spectra-extension-{$folder_name}-style";

		wp_enqueue_style(
			$handle,
			SPECTRA_URL . "build/styles/extensions/{$folder_name}.css",
			array(),
			filemtime( $style_path )
		);
	}
}
